[package]
name = "andrey"
version = "0.1.0"
authors = ["Aarni Koskela <akx@iki.fi>"]
edition = "2021"

[lib]
name = "andrey"
path = "src/lib.rs"

[[bin]]
name = "andrey"
path = "src/bin/main.rs"

[dependencies]
rand = "0.8.3"
clap = "2.33.3"
